/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.rfidicecek.frm;

import com.gazi.rfidicecek.db.bl.YoneticiIslem;
import com.gazi.rfidicecek.model.Yonetici;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class frmGiris extends javax.swing.JFrame {

    YoneticiIslem yi = new YoneticiIslem();

    /**
     * Creates new form GirisEkrani
     */
    public frmGiris() {
        initComponents();
        if (yi.YoneticiVarMi()) {
            btnKayit.setVisible(false);
        }
    }

    private void GirisYap() {
        Yonetici y = new Yonetici();
        y.setKullaniciAd(txtKullaniciAdi.getText());
        char[] pass = txtSifre.getPassword();
        String sifre = "";
        for (int i = 0; i < pass.length; i++) {
            sifre += pass[i];
        }
        y.setSifre(sifre);
        if (yi.GirisDogruMu(y)) {
            lblGiris.setText("Giriş başarılı. Yönlendiriliyorsunuz...");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex.getMessage());
            }
            this.dispose();
            frmMenu f = new frmMenu();
            f.setVisible(true);

        } else {
            lblGiris.setText("Hatalı giriş! Lütfen tekrar deneyiniz.");
            txtKullaniciAdi.setText("");
            txtSifre.setText("");
            txtKullaniciAdi.grabFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblGiris3 = new javax.swing.JLabel();
        pnlKapat = new javax.swing.JPanel();
        lblKapat = new javax.swing.JLabel();
        lblGiris2 = new javax.swing.JLabel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        lblGiris = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();
        btnSifreYenile = new javax.swing.JButton();
        btnKayit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YÖNETİCİ GİRİŞ");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(null);

        pnlLeft.setBackground(new java.awt.Color(0, 153, 153));
        pnlLeft.setPreferredSize(new java.awt.Dimension(512, 600));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/icon1.png"))); // NOI18N

        lblGiris3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblGiris3.setForeground(new java.awt.Color(255, 255, 255));
        lblGiris3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiris3.setText("YÖNETİCİ GİRİŞ");

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblGiris3))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGiris3)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pnlMain.add(pnlLeft);
        pnlLeft.setBounds(0, 0, 512, 600);

        pnlKapat.setBackground(new java.awt.Color(0, 153, 153));
        pnlKapat.setAlignmentX(0.0F);

        lblKapat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblKapat.setForeground(new java.awt.Color(255, 255, 255));
        lblKapat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKapat.setText("X");
        lblKapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKapatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKapatLayout = new javax.swing.GroupLayout(pnlKapat);
        pnlKapat.setLayout(pnlKapatLayout);
        pnlKapatLayout.setHorizontalGroup(
            pnlKapatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKapatLayout.createSequentialGroup()
                .addComponent(lblKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlKapatLayout.setVerticalGroup(
            pnlKapatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKapat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        pnlMain.add(pnlKapat);
        pnlKapat.setBounds(990, 0, 40, 34);

        lblGiris2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblGiris2.setForeground(new java.awt.Color(102, 102, 102));
        lblGiris2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiris2.setText("GİRİŞ YAP");
        pnlMain.add(lblGiris2);
        lblGiris2.setBounds(690, 60, 160, 40);

        lblKullaniciAdi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblKullaniciAdi.setText("Yönetici Kullanıcı Adı");
        pnlMain.add(lblKullaniciAdi);
        lblKullaniciAdi.setBounds(570, 140, 310, 22);

        lblSifre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblSifre.setText("Yönetici Şifre");
        pnlMain.add(lblSifre);
        lblSifre.setBounds(570, 210, 330, 30);

        lblGiris.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pnlMain.add(lblGiris);
        lblGiris.setBounds(570, 290, 330, 50);

        txtKullaniciAdi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtKullaniciAdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        txtKullaniciAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKullaniciAdiKeyTyped(evt);
            }
        });
        pnlMain.add(txtKullaniciAdi);
        txtKullaniciAdi.setBounds(570, 170, 400, 40);

        txtSifre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        txtSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSifreKeyTyped(evt);
            }
        });
        pnlMain.add(txtSifre);
        txtSifre.setBounds(570, 240, 400, 40);

        btnGiris.setBackground(new java.awt.Color(255, 255, 255));
        btnGiris.setForeground(new java.awt.Color(255, 255, 255));
        btnGiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/icon2.png"))); // NOI18N
        btnGiris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });
        pnlMain.add(btnGiris);
        btnGiris.setBounds(880, 290, 90, 50);

        btnSifreYenile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnSifreYenile.setText("ŞİFREMİ UNUTTUM");
        btnSifreYenile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        pnlMain.add(btnSifreYenile);
        btnSifreYenile.setBounds(570, 370, 400, 40);

        btnKayit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKayit.setText("YÖNETİCİ KAYIT");
        btnKayit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });
        pnlMain.add(btnKayit);
        btnKayit.setBounds(570, 420, 400, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblKapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKapatMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Sistemi kapatmak istiyor musunuz?", "Çıkılsın mı?", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_lblKapatMouseClicked

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        frmYoneticiKayit f = new frmYoneticiKayit();
        f.setVisible(true);
    }//GEN-LAST:event_btnKayitActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        GirisYap();
    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtKullaniciAdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKullaniciAdiKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            txtSifre.requestFocus();
        }
    }//GEN-LAST:event_txtKullaniciAdiKeyTyped

    private void txtSifreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSifreKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            GirisYap();
        }
    }//GEN-LAST:event_txtSifreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKayit;
    private javax.swing.JButton btnSifreYenile;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblGiris;
    private javax.swing.JLabel lblGiris2;
    private javax.swing.JLabel lblGiris3;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblKapat;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JPanel pnlKapat;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
