/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.rfidicecek.frm;

import javax.swing.JOptionPane;


/**
 *
 * @author asus
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        icnKullaniciEkle = new javax.swing.JLabel();
        icnParaYukle = new javax.swing.JLabel();
        icnYoneticiEkle = new javax.swing.JLabel();
        icnUrunEkle = new javax.swing.JLabel();
        btnKullaniciIslemleri = new javax.swing.JButton();
        btnParaYukle = new javax.swing.JButton();
        btnSatis = new javax.swing.JButton();
        btnYoneticiKayit = new javax.swing.JButton();
        btnUrunKayit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSatisListe = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(204, 204, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1024, 600));

        icnKullaniciEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/user.png"))); // NOI18N

        icnParaYukle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/money.png"))); // NOI18N

        icnYoneticiEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/vvvvvvvvvvv.png"))); // NOI18N

        icnUrunEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/kahve.png"))); // NOI18N

        btnKullaniciIslemleri.setBackground(new java.awt.Color(255, 255, 204));
        btnKullaniciIslemleri.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKullaniciIslemleri.setText("KULLANICI İŞLEMLERİ");
        btnKullaniciIslemleri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnKullaniciIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciIslemleriActionPerformed(evt);
            }
        });

        btnParaYukle.setBackground(new java.awt.Color(255, 255, 204));
        btnParaYukle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnParaYukle.setText("PARA YÜKLE");
        btnParaYukle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnParaYukle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaYukleActionPerformed(evt);
            }
        });

        btnSatis.setBackground(new java.awt.Color(255, 255, 204));
        btnSatis.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnSatis.setText("SATIŞ İŞLEMLERİ");
        btnSatis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisActionPerformed(evt);
            }
        });

        btnYoneticiKayit.setBackground(new java.awt.Color(255, 255, 204));
        btnYoneticiKayit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnYoneticiKayit.setText("YÖNETİCİ EKLE");
        btnYoneticiKayit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnYoneticiKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoneticiKayitActionPerformed(evt);
            }
        });

        btnUrunKayit1.setBackground(new java.awt.Color(255, 255, 204));
        btnUrunKayit1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnUrunKayit1.setText("ÜRÜN İŞLEMLERİ");
        btnUrunKayit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUrunKayit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunKayit1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/Webp.net-resizeimage.png"))); // NOI18N

        btnSatisListe.setBackground(new java.awt.Color(255, 255, 204));
        btnSatisListe.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnSatisListe.setText("SATIŞ LİSTESİ");
        btnSatisListe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSatisListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisListeActionPerformed(evt);
            }
        });

        btnCikis.setBackground(new java.awt.Color(255, 255, 204));
        btnCikis.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnCikis.setText("ÇIKIŞ");
        btnCikis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/Webp.net-resizeimage (2).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/Webp.net-resizeimage (1).png"))); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(icnKullaniciEkle))
                    .addComponent(icnParaYukle)
                    .addComponent(icnYoneticiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKullaniciIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParaYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYoneticiKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(304, 304, 304)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUrunKayit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSatis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSatisListe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCikis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(icnUrunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icnUrunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnUrunKayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(btnCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(btnSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnSatisListe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(icnKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(icnParaYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(icnYoneticiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnKullaniciIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnParaYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnYoneticiKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYoneticiKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoneticiKayitActionPerformed
        frmYoneticiKayit f = new frmYoneticiKayit();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnYoneticiKayitActionPerformed

    private void btnKullaniciIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciIslemleriActionPerformed
        frmKullaniciIslemleri f = new frmKullaniciIslemleri();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKullaniciIslemleriActionPerformed

    private void btnSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisActionPerformed
        frmSatis f = new frmSatis();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSatisActionPerformed

    private void btnParaYukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaYukleActionPerformed
        frmParaYukle frm= new frmParaYukle();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnParaYukleActionPerformed

    private void btnUrunKayit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunKayit1ActionPerformed
        frmUrunIslemleri f = new frmUrunIslemleri();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUrunKayit1ActionPerformed

    private void btnSatisListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisListeActionPerformed
        frmSatisList f = new frmSatisList();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSatisListeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Çıkış yapmak istediğinize emin misiniz?") == JOptionPane.YES_OPTION) {
            frmGiris f = new frmGiris();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Çıkış yapmak istediğinize emin misiniz?") == JOptionPane.YES_OPTION) {
            frmGiris f = new frmGiris();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCikisActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnKullaniciIslemleri;
    private javax.swing.JButton btnParaYukle;
    private javax.swing.JButton btnSatis;
    private javax.swing.JButton btnSatisListe;
    private javax.swing.JButton btnUrunKayit1;
    private javax.swing.JButton btnYoneticiKayit;
    private javax.swing.JLabel icnKullaniciEkle;
    private javax.swing.JLabel icnParaYukle;
    private javax.swing.JLabel icnUrunEkle;
    private javax.swing.JLabel icnYoneticiEkle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
