/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.rfidicecek.frm;

import com.gazi.rfidicecek.db.bl.KullaniciIslem;
import com.gazi.rfidicecek.db.bl.SatisIslem;
import com.gazi.rfidicecek.db.bl.UrunIslem;
import com.gazi.rfidicecek.model.Kullanici;
import com.gazi.rfidicecek.model.Satis;
import com.gazi.rfidicecek.model.Urun;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author asus
 */
public class frmSatis extends javax.swing.JFrame {
    
    Kullanici k = new Kullanici();
    UrunIslem ui = new UrunIslem();
    KullaniciIslem ki = new KullaniciIslem();
    List<Urun> list = ui.UrunListele();
    List<JCheckBox> check = new ArrayList<>();
    List<Satis> secilen = new ArrayList<>();
    List<JSpinner> spin = new ArrayList<>();
    List<JLabel> label = new ArrayList<>();
    String rfid = "";
    Font font = new Font("Calibri", 0, 18);
    
    public frmSatis() {
        initComponents();
    }
    
    public void loadList() {
        for (int i = 0; i < list.size(); i++) {
            JCheckBox cb = new JCheckBox();
            cb.setBounds(20, i * 50 + 35, 250, 50);
            cb.setName(String.valueOf(list.get(i).getId()));
            cb.setText(list.get(i).getAd());
            cb.setFont(font);
            check.add(cb);
            pnlLeft.add(cb);
            
            JSpinner sp = new JSpinner();
            sp.setBounds(300, i * 50 + 35, 50, 50);
            sp.setName(String.valueOf(list.get(i).getId()));
            SpinnerModel sm = new SpinnerNumberModel(1, 1, 10, 1);
            sp.setModel(sm);
            spin.add(sp);
            pnlLeft.add(sp);
            
            JLabel lbl = new JLabel();
            lbl.setBounds(380, i * 50 + 35, 50, 50);
            lbl.setText(String.valueOf(list.get(i).getFiyat()));
            lbl.setFont(font);
            label.add(lbl);
            pnlLeft.add(lbl);
            
            JLabel lb = new JLabel();
            lb.setBounds(430, i * 50 + 35, 50, 50);
            lb.setText("TL");
            lb.setFont(font);
            pnlLeft.add(lb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSatis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAdSoyad = new javax.swing.JTextField();
        btnRfid = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlLeft.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Ürün");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Miktar");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Birim Fiyat");

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(179, 179, 179))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSatis.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnSatis.setText("SATIŞ");
        btnSatis.setEnabled(false);
        btnSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("AD SOYAD");

        txtAdSoyad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAdSoyad.setEnabled(false);

        btnRfid.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnRfid.setText("RFID");
        btnRfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRfidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSatis, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtAdSoyad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRfid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnRfid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfidActionPerformed
        rfid = ki.RfidOku();
        if (rfid == null || rfid.equals("")) {
            return;
        }
        btnSatis.setEnabled(true);
        
        for (int i = 0; i < check.size(); i++) {
            if (check.get(i).isSelected()) {
                System.out.println(check.get(i).getName());
            }
        }
        
        k = ki.KullaniciGetir(rfid);
        if (k == null) {
            JOptionPane.showMessageDialog(null, "Bu RFID ile kayıtlı kullanıcı bulunamadı.");
        }
        btnSatis.setEnabled(true);
        txtAdSoyad.setText(k.getAdSoyad());
    }//GEN-LAST:event_btnRfidActionPerformed

    private void btnSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisActionPerformed
        double tutar = 0;
        secilen.clear();
        for (int i = 0; i < spin.size(); i++) {
            if (check.get(i).isSelected()) {
                Satis s = new Satis();
                s.SetKullaniciId(k.getId());
                s.SetUrunId(Integer.parseInt(check.get(i).getName()));
                s.SetAdet((int) spin.get(i).getValue());
                s.SetTutar(s.getAdet() * Float.parseFloat(label.get(i).getText()));
                secilen.add(s);
            }
        }
        for (int i = 0; i < secilen.size(); i++) {
            tutar += secilen.get(i).getTutar();
        }
        if (k.getBakiye() < tutar) {
            JOptionPane.showMessageDialog(null, "YETERSİZ BAKİYE");
            return;
        }
        for (int i = 0; i < secilen.size(); i++) {
            SatisIslem si = new SatisIslem();
            if (si.SatisYap(secilen.get(i), k.getBakiye())) {
                JOptionPane.showMessageDialog(null, "Satış başarılı.");
            }
        }
        

    }//GEN-LAST:event_btnSatisActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmMenu f = new frmMenu();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadList();
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSatis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRfid;
    private javax.swing.JButton btnSatis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JTextField txtAdSoyad;
    // End of variables declaration//GEN-END:variables
}
