/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.rfidicecek.frm;

import com.gazi.rfidicecek.db.bl.KullaniciIslem;
import com.gazi.rfidicecek.db.bl.SatisIslem;
import com.gazi.rfidicecek.model.Kullanici;
import com.gazi.rfidicecek.model.TableModel;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emin
 */
public class frmSatisList extends javax.swing.JFrame {

    /**
     * Creates new form frmSatisList
     */
    SimpleDateFormat mf = new SimpleDateFormat("yyyy-MM-dd");

    public frmSatisList() {
        initComponents();
    }

    void TabloDoldur() {
        SatisIslem si = new SatisIslem();
        DefaultTableModel dtm = (DefaultTableModel)tblList.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            dtm.removeRow(i);
        }
        try {
            Date basTarih = dateBas.getDate();
            Date sonTarih = dateBit.getDate();
            String bas = mf.format(basTarih);
            String son = mf.format(sonTarih);
            if (sonTarih.before(basTarih)) {
                JOptionPane.showMessageDialog(null, "Bitiş tarihi başlangıç tarihinden önce olamaz.");
                return;
            }
            String ad = cmbKullanici.getSelectedItem().toString();
            List<TableModel> satisList = si.SatisList(bas, son, ad);
            if (satisList == null || satisList.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kayıt bulunamadı.");
            }
            Object rowData[] = new Object[5];
            for (int i = 0; i < satisList.size(); i++) {
                rowData[0] = satisList.get(i).getAdSoyad();
                rowData[1] = satisList.get(i).getUrun();
                rowData[2] = satisList.get(i).getAdet();
                rowData[3] = satisList.get(i).getTutar() + "TL";
                rowData[4] = satisList.get(i).getTarih();
                dtm.addRow(rowData);
            }
        } catch (HeadlessException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splinPane = new javax.swing.JSplitPane();
        pnlTop = new javax.swing.JPanel();
        dateBas = new org.jdesktop.swingx.JXDatePicker();
        dateBit = new org.jdesktop.swingx.JXDatePicker();
        cmbKullanici = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnListele = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        splinPane.setDividerLocation(100);
        splinPane.setDividerSize(0);
        splinPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splinPane.setMinimumSize(new java.awt.Dimension(1024, 100));
        splinPane.setPreferredSize(new java.awt.Dimension(1024, 100));

        pnlTop.setBackground(new java.awt.Color(0, 153, 153));

        cmbKullanici.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmbKullanici.setMaximumRowCount(100);
        cmbKullanici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tümü" }));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Başlangıç");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Bitiş");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Kullanıcı");

        btnListele.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(dateBas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(dateBit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(cmbKullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85)))
                .addComponent(btnListele)
                .addGap(419, 419, 419))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKullanici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnListele)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        splinPane.setTopComponent(pnlTop);

        pnlBottom.setLayout(new java.awt.BorderLayout());

        tblList.setBackground(new java.awt.Color(204, 255, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad Soyad", "Ürün", "Adet", "Tutar", "Tarih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setResizable(false);
            tblList.getColumnModel().getColumn(1).setResizable(false);
            tblList.getColumnModel().getColumn(2).setResizable(false);
            tblList.getColumnModel().getColumn(3).setResizable(false);
            tblList.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlBottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        splinPane.setRightComponent(pnlBottom);

        getContentPane().add(splinPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmMenu f = new frmMenu();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        TabloDoldur();
    }//GEN-LAST:event_btnListeleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dateBas.setDate(Date.from(Instant.now()));
        dateBit.setDate(Date.from(Instant.now()));
        KullaniciIslem ki = new KullaniciIslem();
        List<Kullanici> kList = ki.KullaniciList();
        for (int i = 0; i < kList.size(); i++) {
            cmbKullanici.addItem(kList.get(i).getAdSoyad());
        }
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSatisList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSatisList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSatisList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSatisList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSatisList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListele;
    private javax.swing.JComboBox<String> cmbKullanici;
    private org.jdesktop.swingx.JXDatePicker dateBas;
    private org.jdesktop.swingx.JXDatePicker dateBit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JSplitPane splinPane;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
