/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.rfidicecek.frm;

import com.gazi.rfidicecek.db.bl.YoneticiIslem;
import com.gazi.rfidicecek.model.Yonetici;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmYoneticiKayit extends javax.swing.JFrame {

        String sifre = "";
        String sifre2 = "";
        String kullaniciAdi = "";
    /**
     * Creates new form frmYoneticiKayit
     */
    public frmYoneticiKayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        txtKullaniciAdi = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSifreTekrar = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGiris2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" ŞİFRE");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 160, 30));
        jPanel1.add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 220, 30));
        jPanel1.add(txtKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 220, 30));

        btnKaydet.setBackground(new java.awt.Color(255, 255, 255));
        btnKaydet.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKaydet.setText("KAYIT OL");
        btnKaydet.setActionCommand("");
        btnKaydet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        jPanel1.add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 150, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" KULLANICI ADI");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 160, 30));
        jPanel1.add(txtSifreTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 220, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" ŞİFRE TEKRAR");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 160, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/rfidicecek/img/yoneticiii.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 340));

        lblGiris2.setBackground(new java.awt.Color(255, 255, 255));
        lblGiris2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblGiris2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiris2.setText("YÖNETİCİ KAYIT");
        lblGiris2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblGiris2.setOpaque(true);
        jPanel1.add(lblGiris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 400, 60));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        sifre = "";
        sifre2 = "";
        kullaniciAdi = txtKullaniciAdi.getText().trim();
        YoneticiIslem yi = new YoneticiIslem();
        if (yi.KullaniciAdiOzelMi(kullaniciAdi)) {
            JOptionPane.showMessageDialog(null, "Bu kullanıcı adı daha önce alınmış. Lütfen başka kullanıcı adıyla deneyin.");
            return;
        }
        char[] pass = txtSifre.getPassword();
        for (int i = 0; i < pass.length; i++) {
            sifre += pass[i];
        }
        char[] pass2 = txtSifreTekrar.getPassword();
        for (int i = 0; i < pass2.length; i++) {
            sifre2 += pass[i];
        }
        if (txtKullaniciAdi.getText().equals("") || txtKullaniciAdi.getText() == null) {
            JOptionPane.showMessageDialog(null, "Kullanıcı adı boş geçilemez.");
            System.out.println(txtKullaniciAdi.getText());
            return;
        }
        if (!sifre.equals(sifre2) || sifre == null || sifre.equals("") || sifre2 == null || sifre2.equals("")) {
            JOptionPane.showMessageDialog(null, "Şifreler uyuşmuyor. Lütfen tekrar giriniz.");
            System.out.println(sifre + " " + sifre2);
            return;
        }
        Yonetici y = new Yonetici();
        y.setKullaniciAd(kullaniciAdi);
        y.setSifre(sifre);
        if (yi.YoneticiKayit(y)) {
            JOptionPane.showMessageDialog(null, "Yönetici kayıt işlemi başarılı.");
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmMenu f = new frmMenu();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmYoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmYoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmYoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmYoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmYoneticiKayit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGiris2;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    private javax.swing.JPasswordField txtSifreTekrar;
    // End of variables declaration//GEN-END:variables
}
